import {StyleSheet, Dimensions} from 'react-native';
import {color} from '../../Utils/Color';

const Color = color;

const styles = StyleSheet.create({
  loadingButton: {
    width: 80,
    marginVertical: 5,
  },
  screen: {
    // paddingBottom: (100),
    // marginBottom: (70),
    backgroundColor: Color.white,
    // backgroundColor: 'red',
  },
  containerStyle: {
    // backgroundColor: 'blue',
    paddingTop: 10,
    // marginBottom: (70),
    paddingBottom: 100,
    // paddingBottom: (10),
    backgroundColor: Color.white,
  },
  touchableWithoutFeedback: {
    backgroundColor: 'red',
    // backgroundColor: Color.white,
  },
  inputTextContainer: {
    // position: 'absolute',
    // top: height / 1.2,
    bottom: 0,
    // bottom: (70),
    // left: (10),
    flexDirection: 'row',
    // backgroundColor: 'red',
    // marginBottom: (20),
    marginHorizontal: 10,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
    width: '75%',
    // height: (38),
    backgroundColor: Color.white,
    // backgroundColor: 'red',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 2,

    // zIndex: 2000,
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    borderRadius: 8,
    height: 40,
    // backgroundColor: 'red',
    // backgroundColor: Color.white,
  },
  button: {
    flexDirection: 'row',
    backgroundColor: Color.primary,
    justifyContent: 'center',
    alignItems: 'center',
    width: 45,
    height: 40,
    borderRadius: 8,
    // right: (-20),
    // alignSelf: 'flex-end',
  },
  buttonIcon: {
    width: 20,
    height: 20,
  },
  textInput: {
    // marginHorizontal: (10),
    // paddingHorizontal: (5),
    paddingLeft: 10,
    // backgroundColor: 'blue',
    width: '100%',
    fontSize: 14,
    color: Color.text,
    // height: (38),
  },
  image: {
    width: 80,
    height: 70,
    borderRadius: 50,
    backgroundColor: '#e8e8e8',
  },
  ImagePreviewContainer: {
    position: 'absolute',
    bottom: 65,
    left: 10,
    backgroundColor: Color.white,
    marginHorizontal: 20,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    marginBottom: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  imagePreview: {
    borderRadius: 8,
    width: 130,
    height: 150,
    marginBottom: 10,
  },
  cancelImageIcon: {
    position: 'absolute',
    right: 3,
    zIndex: 1000,
  },
  preview: {
    width: 130,
    height: 150,
  },
  recieverMain: {
    alignSelf: 'flex-start',
  },
  senderMain: {
    alignSelf: 'flex-end',
  },
  reciever: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    backgroundColor: Color.greyLight,
    borderRadius: 8,
    borderBottomLeftRadius: 0,
    marginLeft: 20,
    marginBottom: 5,
    maxWidth: '80%',
    position: 'relative',
  },
  sender: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    justifyContent: 'center',
    backgroundColor: Color.primary,
    // alignSelf: 'flex-end',
    borderRadius: 8,
    borderBottomRightRadius: 0,
    marginRight: 20,
    marginBottom: 5,
    maxWidth: '80%',
    position: 'relative',
  },
  recieverText: {
    paddingHorizontal: 5,
    color: Color.basic,
    marginLeft: 10,
    // marginBottom: 15,
    fontSize: 12,
  },
  senderText: {
    paddingHorizontal: 5,
    color: Color.chat,
    marginRight: 10,
    fontSize: 12,
    // marginBottom: 15,
  },
  messageSenderTime: {
    fontSize: 12,
    alignSelf: 'flex-end',
    marginBottom: 3,
    marginHorizontal: 20,
    color: Color.icon,
    justifyContent: 'space-between',
    // width: (65),
  },
  messageRecieverTime: {
    fontSize: 12,
    alignSelf: 'flex-start',
    marginHorizontal: 20,
    marginBottom: 3,
    color: Color.icon,
  },
  messageImage: {
    width: 150,
    height: 150,
    borderRadius: 8,
  },
  camerIconCaontainer: {
    alignItems: 'center',
    justifyContent: 'center',
    // marginBottom: (5),
  },
  inputContainerView: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: Color.white,
    marginHorizontal: 20,
  },
  reasonView: {
    // alignSelf: 'flex-start',
    paddingVertical: 10,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
  },
  reasonContentView: {
    borderRadius: 8,
    paddingVertical: 5,
    backgroundColor: Color.secondary,
    paddingHorizontal: 25,
  },
  reasonForVisitText: {
    fontSize: 12,
    // Color: Color.white,
  },
  emptyChatView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 70,
    // height: 100,
    // backgroundColor: 'red',
  },
  emptyChat: {
    alignSelf: 'center',
  },
  inputMainView: {
    paddingBottom: 15,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    // borderRadius: (8),
    // backgroundColor: 'red',
  },
  encryptionBox: {
    marginHorizontal: 20,
    paddingVertical: 4,
    backgroundColor: Color.grey,
    paddingHorizontal: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  DateBox: {
    width: 40,
    marginVertical: 5,
    marginHorizontal: 20,
    paddingVertical: 4,
    // backgroundColor: Color.grey,
    paddingHorizontal: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  encryptionText: {
    fontSize: 11,
  },
  lockIcon: {
    height: 20,
    width: 20,
    marginRight: 10,
  },
  dateText: {
    color: Color.textLight,
  },
  dividerDate: {
    borderWidth: 1,
    width: Dimensions.get('screen').width / 3.5,
    marginHorizontal: 10,
    borderColor: Color.grey,
  },
});

export default styles;
