import { StyleSheet, Dimensions } from 'react-native';
import {
  color,
  font,
  resize,
  heightScale,
  widthScale,
  widthScaleSub,
  square,
  width,
  height,
  // StyleSheet,
} from 'globalStyle';
const styles = StyleSheet.create({
  loadingButton: {
    width: widthScaleSub(80),
    marginVertical: heightScale(5),
  },
  screen: {
    // paddingBottom: heightScale(100),
    // marginBottom: heightScale(70),
    backgroundColor: color.white,
    // backgroundColor: 'red',
  },
  containerStyle: {
    // backgroundColor: 'blue',
    paddingTop: heightScale(10),
    // marginBottom: heightScale(70),
    paddingBottom: heightScale(100),
    // paddingBottom: heightScale(10),
    backgroundColor: color.white,
  },
  touchableWithoutFeedback: {
    backgroundColor: 'red',
    // backgroundColor: color.white,
  },
  inputTextContainer: {
    // position: 'absolute',
    // top: height / 1.2,
    bottom: 0,
    // bottom: heightScale(70),
    // left: widthScale(10),
    flexDirection: 'row',
    // backgroundColor: 'red',
    // marginBottom: widthScale(20),
    marginHorizontal: widthScale(10),
    paddingHorizontal: widthScale(20),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: heightScale(8),
    width: widthScaleSub(120),
    // height: heightScale(38),
    backgroundColor: color.white,
    // backgroundColor: 'red',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 2,

    // zIndex: 2000,
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '130%',
    borderRadius: heightScale(8),
    height: heightScale(40),
    // backgroundColor: 'red',
    // backgroundColor: color.white,
  },
  button: {
    flexDirection: 'row',
    backgroundColor: color.primary,
    justifyContent: 'center',
    alignItems: 'center',
    width: widthScale(45),
    height: heightScale(40),
    borderRadius: heightScale(8),
    // right: widthScale(-20),
    // alignSelf: 'flex-end',
  },
  buttonIcon: {
    width: heightScale(20),
    height: heightScale(20),
  },
  textInput: {
    // marginHorizontal: widthScale(10),
    // paddingHorizontal: widthScale(5),
    paddingLeft: widthScale(10),
    // backgroundColor: 'blue',
    width: '80%',
    fontFamily: 'Poppins-Regular',
    fontSize: heightScale(14),
    color: color.text,
    // height: heightScale(38),
  },
  image: {
    width: widthScale(80),
    height: heightScale(70),
    borderRadius: heightScale(50),
    backgroundColor: '#e8e8e8',
  },
  ImagePreviewContainer: {
    position: 'absolute',
    bottom: heightScale(65),
    left: widthScale(10),
    backgroundColor: color.white,
    marginHorizontal: widthScale(20),
    borderTopLeftRadius: heightScale(8),
    borderTopRightRadius: heightScale(8),
    marginBottom: heightScale(5),
    paddingHorizontal: widthScale(10),
    paddingVertical: widthScale(10),
  },
  imagePreview: {
    borderRadius: heightScale(8),
    width: widthScale(130),
    height: heightScale(150),
    marginBottom: heightScale(10),
  },
  cancelImageIcon: {
    position: 'absolute',
    right: widthScale(3),
    zIndex: 1000,
  },
  preview: {
    width: widthScale(130),
    height: heightScale(150),
  },
  recieverMain: {
    alignSelf: 'flex-start',
  },
  senderMain: {
    alignSelf: 'flex-end',
  },
  reciever: {
    paddingVertical: heightScale(5),
    paddingHorizontal: widthScale(5),
    backgroundColor: color.greyLight,
    borderRadius: heightScale(8),
    borderBottomLeftRadius: 0,
    marginLeft: widthScale(20),
    marginBottom: widthScale(5),
    maxWidth: '80%',
    position: 'relative',
  },
  sender: {
    paddingVertical: heightScale(5),
    paddingHorizontal: widthScale(5),
    justifyContent: 'center',
    backgroundColor: color.primary,
    // alignSelf: 'flex-end',
    borderRadius: heightScale(8),
    borderBottomRightRadius: 0,
    marginRight: widthScale(20),
    marginBottom: widthScale(5),
    maxWidth: '80%',
    position: 'relative',
  },
  recieverText: {
    paddingHorizontal: widthScale(5),
    color: color.basic,
    marginLeft: widthScale(10),
    // marginBottom: 15,
    fontSize: heightScale(12),
  },
  senderText: {
    paddingHorizontal: widthScale(5),
    color: color.chat,
    marginRight: widthScale(10),
    fontSize: heightScale(12),
    // marginBottom: 15,
  },
  messageSenderTime: {
    fontSize: heightScale(12),
    alignSelf: 'flex-end',
    marginBottom: widthScale(3),
    marginHorizontal: widthScale(20),
    color: color.icon,
    justifyContent: 'space-between',
    // width: widthScale(65),
  },
  messageRecieverTime: {
    fontSize: heightScale(12),
    alignSelf: 'flex-start',
    marginHorizontal: widthScale(20),
    marginBottom: widthScale(3),
    color: color.icon,
  },
  messageImage: {
    width: widthScale(150),
    height: heightScale(150),
    borderRadius: heightScale(8),
  },
  camerIconCaontainer: {
    alignItems: 'center',
    justifyContent: 'center',
    // marginBottom: heightScale(5),
  },
  inputContainerView: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: color.white,
    marginHorizontal: widthScale(20),
  },
  reasonView: {
    // alignSelf: 'flex-start',
    paddingVertical: heightScale(10),
    backgroundColor: color.white,
    paddingHorizontal: widthScale(20),
  },
  reasonContentView: {
    borderRadius: heightScale(8),
    paddingVertical: heightScale(5),
    backgroundColor: color.secondary,
    paddingHorizontal: widthScale(25),
  },
  reasonForVisitText: {
    fontSize: heightScale(12),
    // color: color.white,
  },
  emptyChatView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: heightScale(70),
    // height: 100,
    // backgroundColor: 'red',
  },
  emptyChat: {
    alignSelf: 'center',
  },
  inputMainView: {
    paddingBottom: heightScale(15),
    backgroundColor: color.white,
    paddingHorizontal: widthScale(20),
    // borderRadius: heightScale(8),
    // backgroundColor: 'red',
  },
  encryptionBox: {
    marginHorizontal: widthScale(20),
    paddingVertical: heightScale(4),
    backgroundColor: color.grey,
    paddingHorizontal: widthScale(10),
    borderRadius: heightScale(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  DateBox: {
    width: widthScaleSub(40),
    marginVertical: heightScale(5),
    marginHorizontal: widthScale(20),
    paddingVertical: heightScale(4),
    // backgroundColor: color.grey,
    paddingHorizontal: widthScale(10),
    borderRadius: heightScale(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  encryptionText: {
    fontSize: heightScale(11),
  },
  lockIcon: {
    height: heightScale(20),
    width: heightScale(20),
    marginRight: widthScale(10),
  },
  dateText: {
    color: color.textLight,
  },
  dividerDate: {
    borderWidth: heightScale(1),
    width: Dimensions.get('screen').width / 3.5,
    marginHorizontal: widthScale(10),
    borderColor: color.grey,
  },
});

export default styles;
