export const accounts = [
  {
    accessToken: 'syt_amFja2ll_sWdVxbTCIJLoRyvxFIhq_3Ozad8',
    access_token: 'syt_amFja2ll_sWdVxbTCIJLoRyvxFIhq_3Ozad8',
    crypto: true,
    deviceId: 'FJUCSXSWIT',
    device_id: 'FJUCSXSWIT',
    error: false,
    expires_in_ms: 299932,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@jackie:localhost',
    user_id: '@jackie:localhost',
  },
  {
    accessToken: 'syt_ZmF6eg_IDYGYkAgrZOvEYJAbeAg_2uvXSH',
    access_token: 'syt_ZmF6eg_IDYGYkAgrZOvEYJAbeAg_2uvXSH',
    crypto: true,
    deviceId: 'VAZEMYBZXZ',
    device_id: 'VAZEMYBZXZ',
    error: false,
    expires_in_ms: 299932,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@fazz:localhost',
    user_id: '@fazz:localhost',
  },
  {
    accessToken: 'syt_a2l0dHk_NbvhOqhzwuikYBZIUdWu_2vU6Kl',
    access_token: 'syt_a2l0dHk_NbvhOqhzwuikYBZIUdWu_2vU6Kl',
    crypto: true,
    deviceId: 'PKOCKLFOAB',
    device_id: 'PKOCKLFOAB',
    error: false,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@kitty:localhost',
    user_id: '@kitty:localhost',
  },
  {
    accessToken: 'syt_cmVk_NyKpjpmIkxtKYdXSOlQM_1gbCs6',
    access_token: 'syt_cmVk_NyKpjpmIkxtKYdXSOlQM_1gbCs6',
    crypto: true,
    deviceId: 'JQTKDAELEF',
    device_id: 'JQTKDAELEF',
    error: false,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@red:localhost',
    user_id: '@red:localhost',
  },
  {
    accessToken: 'syt_cnlhbg_nVCZyHMnlJdjnKzZsJbv_0UHks1',
    access_token: 'syt_cnlhbg_nVCZyHMnlJdjnKzZsJbv_0UHks1',
    crypto: true,
    deviceId: 'SAWWOPRCMD',
    device_id: 'SAWWOPRCMD',
    error: false,
    expires_in_ms: 299969,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_cnlhbg_dApFhJSovwjzIkLMhcqV_22uxwq',
    userId: '@ryan:localhost',
    user_id: '@ryan:localhost',
  },
  {
    accessToken: 'syt_Z3JlbGlzaA_FSRvAvinTztbYWrkFCMr_48DhHg',
    access_token: 'syt_Z3JlbGlzaA_FSRvAvinTztbYWrkFCMr_48DhHg',
    crypto: true,
    deviceId: 'WBSTPAMMIU',
    device_id: 'WBSTPAMMIU',
    error: false,
    expires_in_ms: 299966,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_Z3JlbGlzaA_gujlkGmlyxPmAGzjMGFr_1Sy9zv',
    userId: '@grelish:localhost',
    user_id: '@grelish:localhost',
    recovery_key: 'EsTj pduk xPxv y5fx NNUd dzyn 7z1S 7kKL qS2c tYDs FSfv 5hGF',
  },
  {
    accessToken: 'syt_dXhoYWRp_yaDQwTiFsTjabgGVKzyP_1hfrV4',
    access_token: 'syt_dXhoYWRp_yaDQwTiFsTjabgGVKzyP_1hfrV4',
    crypto: true,
    deviceId: 'UCSKYFGRGG',
    device_id: 'UCSKYFGRGG',
    error: false,
    expires_in_ms: 299977,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_dXhoYWRp_BsYXQlCmNapZAqZAfLLM_2Sj3VP',
    userId: '@uxhadi:localhost',
    user_id: '@uxhadi:localhost',
  },
  {
    accessToken: 'syt_YW1uYWppcmE_EvLAjWMsCsnfqAOVXQXL_0ye5wr',
    access_token: 'syt_YW1uYWppcmE_EvLAjWMsCsnfqAOVXQXL_0ye5wr',
    crypto: true,
    deviceId: 'KDVJXKDEUZ',
    device_id: 'KDVJXKDEUZ',
    error: false,
    expires_in_ms: 299977,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_YW1uYWppcmE_pIDPEHRfUjkqtMeXxNTt_1pCsIs',
    userId: '@amnajira:localhost',
    user_id: '@amnajira:localhost',
  },
  {
    accessToken: 'syt_c2llZA_zIgbcSxFUGhQuGZlTzeB_4MxHOi',
    access_token: 'syt_c2llZA_zIgbcSxFUGhQuGZlTzeB_4MxHOi',
    crypto: true,
    deviceId: 'DOQXPZUXAO',
    device_id: 'DOQXPZUXAO',
    error: false,
    expires_in_ms: 299966,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_c2llZA_EYzmrEyElKVeIbrTWFEW_2XuK9h',
    userId: '@sied:localhost',
    user_id: '@sied:localhost',
  },
  {
    accessToken: 'syt_Z3JpZWY_sbfOPDZWJidSYXrsDxyx_03iydS',
    access_token: 'syt_Z3JpZWY_sbfOPDZWJidSYXrsDxyx_03iydS',
    crypto: true,
    deviceId: 'CADNLBCBHE',
    device_id: 'CADNLBCBHE',
    error: false,
    expires_in_ms: 299979,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_Z3JpZWY_OloNGdqjgUUtmNMhQXwg_2BDq7J',
    userId: '@grief:localhost',
    user_id: '@grief:localhost',
  },
  {
    accessToken: 'syt_YnJhbmRvbg_yRqGxuqsamyYVDDARcTo_1sTKMm',
    access_token: 'syt_YnJhbmRvbg_yRqGxuqsamyYVDDARcTo_1sTKMm',
    homeserver: 'http://192.168.18.22:8008',
    deviceId: 'TEXXMZAHLJ',
    device_id: 'TEXXMZAHLJ',
    crypto: true,
    error: false,
    expires_in_ms: 299979,
    home_server: 'localhost',
    userId: '@brandon:localhost',
    user_id: '@brandon:localhost',
  },
  {
    accessToken: 'syt_ZmF3YWQ_uNtyrlkJdpvUYRYBfccs_1uf2xJ',
    access_token: 'syt_ZmF3YWQ_uNtyrlkJdpvUYRYBfccs_1uf2xJ',
    crypto: true,
    deviceId: 'PIVMNZSKMI',
    device_id: 'PIVMNZSKMI',
    error: false,
    expires_in_ms: 299956,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_ZmF3YWQ_IZkutGNzWnGZUAfWHGBh_3vQTof',
    userId: '@fawad:localhost',
    user_id: '@fawad:localhost',
  },

  {
    accessToken: 'syt_Y3JlZWQ_gREzjYddkKjRCMZSGUbJ_1XyZkA',
    access_token: 'syt_Y3JlZWQ_gREzjYddkKjRCMZSGUbJ_1XyZkA',
    crypto: true,
    deviceId: 'IUJJAXYOLW',
    device_id: 'IUJJAXYOLW',
    error: false,
    expires_in_ms: 299958,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_Y3JlZWQ_JqMkMmHHVppptBJyxdVg_2cE26P',
    userId: '@creed:localhost',
    user_id: '@creed:localhost',
  },
  {
    accessToken: 'syt_emVuZGF5YQ_tEYsNrmIIoRLqOXrSwgp_4TSMN6',
    access_token: 'syt_emVuZGF5YQ_tEYsNrmIIoRLqOXrSwgp_4TSMN6',
    crypto: true,
    deviceId: 'HEQHALOJWY',
    device_id: 'HEQHALOJWY',
    error: false,
    expires_in_ms: 299965,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_emVuZGF5YQ_XmLiUvhWyvUPskFggBNv_3cpuGX',
    userId: '@zendaya:localhost',
    user_id: '@zendaya:localhost',
  },
  {
    accessToken: 'syt_c29uaWE_RQCaiEwxKQoTxgpualBy_4YlM60',
    access_token: 'syt_c29uaWE_RQCaiEwxKQoTxgpualBy_4YlM60',
    crypto: true,
    deviceId: 'HMCPYPMAFA',
    device_id: 'HMCPYPMAFA',
    error: false,
    expires_in_ms: 299941,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_c29uaWE_JRlOKOyHLDyVFyBVnCxl_3KNNYn',
    userId: '@sonia:localhost',
    user_id: '@sonia:localhost',
  },
  {
    accessToken: 'syt_cm9oYW4_fdYQzPFTcGtWIMQvaGxg_3VvNZy',
    access_token: 'syt_cm9oYW4_fdYQzPFTcGtWIMQvaGxg_3VvNZy',
    crypto: true,
    deviceId: 'MTEPSZONXS',
    device_id: 'MTEPSZONXS',
    error: false,
    expires_in_ms: 299950,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    refresh_token: 'syr_cm9oYW4_DMHwGzvhIzpdbNPaBIrp_0yXGDH',
    userId: '@rohan:localhost',
    user_id: '@rohan:localhost',
  },
];
