export const accounts = [
  {
    accessToken: 'syt_amFja2ll_sWdVxbTCIJLoRyvxFIhq_3Ozad8',
    access_token: 'syt_amFja2ll_sWdVxbTCIJLoRyvxFIhq_3Ozad8',
    crypto: true,
    deviceId: 'FJUCSXSWIT',
    device_id: 'FJUCSXSWIT',
    error: false,
    expires_in_ms: 299932,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@jackie:localhost',
    user_id: '@jackie:localhost',
  },
  {
    accessToken: 'syt_ZmF6eg_IDYGYkAgrZOvEYJAbeAg_2uvXSH',
    access_token: 'syt_ZmF6eg_IDYGYkAgrZOvEYJAbeAg_2uvXSH',
    crypto: true,
    deviceId: 'VAZEMYBZXZ',
    device_id: 'VAZEMYBZXZ',
    error: false,
    expires_in_ms: 299932,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@fazz:localhost',
    user_id: '@fazz:localhost',
  },
  {
    accessToken: 'syt_a2l0dHk_NbvhOqhzwuikYBZIUdWu_2vU6Kl',
    access_token: 'syt_a2l0dHk_NbvhOqhzwuikYBZIUdWu_2vU6Kl',
    crypto: true,
    deviceId: 'PKOCKLFOAB',
    device_id: 'PKOCKLFOAB',
    error: false,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@kitty:localhost',
    user_id: '@kitty:localhost',
  },
  {
    accessToken: 'syt_cmVk_NyKpjpmIkxtKYdXSOlQM_1gbCs6',
    access_token: 'syt_cmVk_NyKpjpmIkxtKYdXSOlQM_1gbCs6',
    crypto: true,
    deviceId: 'JQTKDAELEF',
    device_id: 'JQTKDAELEF',
    error: false,
    home_server: 'localhost',
    homeserver: 'http://192.168.18.22:8008',
    userId: '@red:localhost',
    user_id: '@red:localhost',
  },
];
